wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646750521
    t:
      1:
      - 1
      - 3
      - 5
      4: 3.8.5
      5: 0.12.10
      8:
      - 3
      - 5
