wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646743544
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 1
      - 16
      4: 3.8.5
      5: 0.12.10
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 13
epochs:
  desc: null
  value: 40
gamma:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.0024631818099736347
momentum:
  desc: null
  value: 0.5
pretrained:
  desc: null
  value: 'false'
step_size:
  desc: null
  value: 7
