wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646753755
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 1
      - 19
      4: 3.8.5
      5: 0.12.10
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 14
epochs:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.0044817059218339
log_interval:
  desc: null
  value: 10
momentum:
  desc: null
  value: 0.1
no_cuda:
  desc: null
  value: false
pretrained:
  desc: null
  value: 'false'
seed:
  desc: null
  value: 42
step_size:
  desc: null
  value: 7
test_batch_size:
  desc: null
  value: 10
