wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1646748565
    t:
      1:
      - 1
      - 3
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 19
      4: 3.8.5
      5: 0.12.10
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 4
epochs:
  desc: null
  value: 50
log_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.1
momentum:
  desc: null
  value: 0.1
no_cuda:
  desc: null
  value: false
seed:
  desc: null
  value: 42
test_batch_size:
  desc: null
  value: 10
